### ISSUE TITLE
Website Login icon

### ISSUE THREAD

**Issue by behrouzbk** [AppyBuilder/AppyBuilder#12]
Update website login icon to directly log into http://Gold.AppyBuilder.com

**Comment by PeterMathijssen** [comment]
Could it be possible to change to icon to text, for instance "BUILD NOW!"?

**Comment by behrouzbk** [comment]
Sure, I'll update the site

**Comment by behrouzbk** [comment]
Update completed

**Comment by kkashi01** [comment]
Merged
