### ISSUE TITLE
Location of companion app

### ISSUE THREAD

**Issue by PeterMathijssen** [AppyBuilder/AppyBuilder#15]
Could the companion app have a url of

http://AppyBuilder.com/companion/AppyBuilderGold.apk

Instead of also a versionnumber in the name. When versions change, urls on other places on the net don't point to the actual version anymore. 

It would be the same as how AI does it. 
http://ai2.appinventor.mit.edu/companions/MITAI2Companion.apk

**Comment by kkashi01** [comment]
Done. Thanks for reminder

**Comment by kkashi01** [comment]
Done. Thanks for reminder
