### ISSUE TITLE
LinedTextbox not displaying lines properly in Companion and Compiled apk

### ISSUE THREAD

**Issue by tvleavitt** [AppyBuilder/AppyBuilder#32]
This is strictly demonstrable in the designer, no component logic involved; the screenshots below are from the "Component" outline section of the Designer interface. Note that in this same app, dropping a lined textbox into a vertical arrangement, such that it can completely fill the "card" involved from edge to edge, does not result in lines being offset this way.

Top level vertical arrangement:
![toplevellayout](https://user-images.githubusercontent.com/4445057/35967851-03c90fca-0c77-11e8-8558-8cdbd738a4ea.png)

Horizontal arrangements embedded in the above vertical arrangement:
![embededlayout](https://user-images.githubusercontent.com/4445057/35967849-03aae1d0-0c77-11e8-8ddd-fd4148db4b11.png)

In companion:
![lined_textbox_problem_example_companion](https://user-images.githubusercontent.com/4445057/35967766-b9c9e412-0c76-11e8-8be1-c575edf7e306.png)

In sample compiled apk:
![lined_textbox_problem_example_apk](https://user-images.githubusercontent.com/4445057/35967764-b9ad3d08-0c76-11e8-91e1-5925302f401d.png)

**Comment by Amerkashi** [comment]
@tvleavitt  Could you please post a simple .aia to demo the issue? thanks

**Comment by tvleavitt** [comment]
Was this fixed in the latest release? You can use the SimplyConnect_copy project in my account if needed.

**Comment by Amerkashi** [comment]
@tvleavitt it was fixed. We'll update this issue and close

**Comment by Amerkashi** [comment]
Merged
