### ISSUE TITLE
Notifier ShowTextDialog and ShowChooseDialog have different styles

### ISSUE THREAD

**Issue by gabryk91** [AppyBuilder/AppyBuilder#40]
Choose Dialog:
![image](https://user-images.githubusercontent.com/9896533/36284416-dced848a-12a7-11e8-82d6-c24ae9cabacd.png)

Text Dialog
![image](https://user-images.githubusercontent.com/9896533/36284432-ec33e3bc-12a7-11e8-9983-89263e8b7c91.png)

**Comment by Amerkashi** [comment]
Duplicate of issue: https://github.com/AppyBuilder/AppyBuilder/issues/39

**Comment by gabryk91** [comment]
@Amerkashi @nickonk It's not a duplicate. This is about the style, the looking of the dialog.
Why one is white and the other is black? The notifier is the same...

**Comment by Amerkashi** [comment]
@gabryk91 Once the following update for below ticket is fixed, it will also change the style and will make it uniform

https://github.com/AppyBuilder/AppyBuilder/issues/39
